listen: 0.0.0.0:4222
server_name: chitchat

http_port: 8222

jetstream {
    store_dir: /miren/data/local/jetstream
    max_mem: 256MB
    max_file: 10GB
}

logtime: true
debug: false
trace: false

max_payload: 8MB
max_connections: 1024
